export const TYPES = {
    GameMapper: Symbol("GameMapper"),
    GameService: Symbol("GameService"),
    GameStateMapper: Symbol("GameStateMapper"),
    HSAServerPort: Symbol("HSAServerPort"),
    HSAServerURL: Symbol("HSAServerURL"),
    PaderbornKIPlayerPort: Symbol("PaderbornKIPlayerStartPort"),
    PaderbornKIPlayerURL: Symbol("PaderbornKIPlayerURL"),
    PaderbornKIService: Symbol("PaderbornKIService"),
    PaderbornServerPort: Symbol("PaderbornServerPort"),
    PaderbornServerService: Symbol("PaderbornServerService"),
    PaderbornServerToken: Symbol("PaderbornServerToken"),
    PaderbornServerURL: Symbol("PaderbornServerURL"),
    PlayerMapper: Symbol("PlayerMapper"),
    PlayerService: Symbol("PlayerService"),
};
